### ISSUE TITLE
undefined method `Pathname' for main:Object

### ISSUE THREAD

**Issue by Goltergaul** [Goltergaul/definition#14]
$ gem install definition
Fetching: definition-0.5.1.gem (100%)
Successfully installed definition-0.5.1
Parsing documentation for definition-0.5.1
Installing ri documentation for definition-0.5.1
Done installing documentation for definition after 0 seconds
1 gem installed
$ irb
2.5.1 :001 > require "definition"
Traceback (most recent call last):
        9: from /home/nih/.rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
        8: from (irb):1
        7: from /home/nih/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        6: from /home/nih/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        5: from /home/nih/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        4: from /home/nih/.rvm/gems/ruby-2.5.1/gems/definition-0.5.1/lib/definition.rb:8:in `<top (required)>'
        3: from /home/nih/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        2: from /home/nih/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        1: from /home/nih/.rvm/gems/ruby-2.5.1/gems/definition-0.5.1/lib/definition/i18n.rb:3:in `<top (required)>'
NoMethodError (undefined method `Pathname' for main:Object)

**Comment by Goltergaul** [comment]
fixed and released as 0.5.2
